package duke;

public enum ErrorMessageType {
    EMPTY_COMMAND,
    INVALID_INDICATOR,
    INVALID_DEADLINE,
    INVALID_EVENT,
    INVALID_TASK_NUMBER,
    INVALID_DESCRIPTION,
    INVALID_ACTION_COMMAND
}