remote_theme: daviddarnes/alembic@4.1.0
plugins:
  - jekyll-remote-theme
  - jekyll-redirect-from
  - jemoji
markdown: kramdown
sass:
  style: compressed
encoding: utf-8
lang: en-US
title: "Skylee Task Manager"
url: "https://skylee03.github.io/skylee-task-manager"
repo: "https://github.com/skylee03/skylee-task-manager"
email: "i@skylee.xyz"
css_inline: true
fonts:
  preconnect_urls:
    - https://fonts.gstatic.com
  font_urls:
    - https://fonts.googleapis.com/css2?family=Alegreya:wght@400;700&display=swap